export function renderWebPanelScript(): string {
  return [
    'var urlInput = document.getElementById("url");',
    'var flowInput = document.getElementById("flow");',
    'var executeButton = document.getElementById("execute-button");',
    'var prefillButton = document.getElementById("prefill-button");',
    'var executionId = document.getElementById("execution-id");',
    'var executionStatus = document.getElementById("execution-status");',
    'var scenarioTitle = document.getElementById("scenario-title");',
    'var executionLogs = document.getElementById("execution-logs");',
    "var pollingToken = null;",
    "window.__forgeQaLoaded = true;",
    "",
    "function renderRecord(record) {",
    "  executionId.textContent = record.id;",
    "  executionStatus.textContent = record.status;",
    '  executionStatus.className = "status-" + record.status;',
    '  scenarioTitle.textContent = record.result && record.result.scenarioTitle ? record.result.scenarioTitle : "-";',
    '  var lines = ["URL: " + record.request.url, "Flow: " + record.request.flow, "", "Status: " + record.status];',
    "  if (record.result && record.result.errorMessage) {",
    '    lines.push("Error: " + record.result.errorMessage);',
    "  }",
    "  if (record.result && record.result.auditEntries && record.result.auditEntries.length) {",
    '    lines.push("", "Audit entries:");',
    "    for (var index = 0; index < record.result.auditEntries.length; index += 1) {",
    "      var entry = record.result.auditEntries[index];",
    '      lines.push("- [" + entry.type + "] " + entry.createdAt);',
    "      lines.push(JSON.stringify(entry.payload, null, 2));",
    "    }",
    "  }",
    '  executionLogs.textContent = lines.join("\\n");',
    "}",
    "",
    "async function pollExecution(id) {",
    "  if (pollingToken) {",
    "    clearInterval(pollingToken);",
    "  }",
    "  var refresh = async function () {",
    '    var response = await fetch("/api/executions/" + id);',
    "    var record = await response.json();",
    "    renderRecord(record);",
    '    if (record.status === "passed" || record.status === "failed") {',
    "      clearInterval(pollingToken);",
    "      pollingToken = null;",
    "    }",
    "  };",
    "  await refresh();",
    "  pollingToken = setInterval(refresh, 1000);",
    "}",
    "",
    'executeButton.addEventListener("click", async function () {',
    "  try {",
    "    var payload = { url: urlInput.value, flow: flowInput.value };",
    '    executionStatus.textContent = "running";',
    '    executionStatus.className = "status-running";',
    '    executionLogs.textContent = "Criando execucao...";',
    '    var response = await fetch("/api/executions", {',
    '      method: "POST",',
    '      headers: { "Content-Type": "application/json" },',
    "      body: JSON.stringify(payload)",
    "    });",
    "    var record = await response.json();",
    "    renderRecord(record);",
    "    await pollExecution(record.id);",
    "  } catch (error) {",
    '    executionStatus.textContent = "failed";',
    '    executionStatus.className = "status-failed";',
    "    executionLogs.textContent = String(error);",
    "  }",
    "});",
    "",
    'prefillButton.addEventListener("click", function () {',
    '  urlInput.value = "/fixtures/login-flow";',
    '  flowInput.value = "Open the login page, submit the form and validate the dashboard state.";',
    "});"
  ].join("\n");
}
