export function renderWebPanelScript(): string {
  return [
    'var urlInput = document.getElementById("url");',
    'var flowInput = document.getElementById("flow");',
    'var executeButton = document.getElementById("execute-button");',
    'var prefillButton = document.getElementById("prefill-button");',
    'var healingDemoButton = document.getElementById("healing-demo-button");',
    'var executionId = document.getElementById("execution-id");',
    'var executionStatus = document.getElementById("execution-status");',
    'var scenarioTitle = document.getElementById("scenario-title");',
    'var executionSummary = document.getElementById("execution-summary");',
    'var executionArtifacts = document.getElementById("execution-artifacts");',
    'var executionHealing = document.getElementById("execution-healing");',
    'var executionLogs = document.getElementById("execution-logs");',
    "var pollingToken = null;",
    "window.__forgeQaLoaded = true;",
    "",
    "function collectHealingEntries(record) {",
    "  var entries = record.result && record.result.auditEntries ? record.result.auditEntries : [];",
    "  var healingEntries = [];",
    "  for (var index = 0; index < entries.length; index += 1) {",
    "    var entry = entries[index];",
    "    if (!entry || entry.type !== 'healing' || !entry.payload || !entry.payload.recoveredSelector) {",
    "      continue;",
    "    }",
    "    healingEntries.push(entry.payload);",
    "  }",
    "  return healingEntries;",
    "}",
    "",
    "function renderSummary(summary) {",
    "  if (!summary) {",
    '    executionSummary.textContent = "Resumo indisponivel.";',
    "    return;",
    "  }",
    "  executionSummary.textContent = [",
    '    "Steps planejados: " + summary.totalSteps,',
    '    "Tentativas de healing: " + summary.healingAttempts,',
    '    "Recuperacoes: " + summary.healedActions,',
    '    "Memory/Fallback/AI: " + summary.memoryRecoveries + "/" + summary.fallbackRecoveries + "/" + summary.aiRecoveries,',
    '    "Falhas finais: " + summary.failedActions,',
    '    "Evidencias: " + summary.evidenceArtifacts,',
    '    "Quality score: " + summary.qualityScore + " (" + summary.qualityLabel + ")",',
    '    "Status final: " + summary.finalStatus',
    '  ].join("\\n");',
    "}",
    "",
    "function renderArtifacts(record) {",
    '  executionArtifacts.innerHTML = "";',
    "  var artifacts = record.result && record.result.artifacts ? record.result.artifacts : [];",
    "  if (!artifacts.length) {",
    '    executionArtifacts.textContent = "Nenhuma evidencia registrada.";',
    "    return;",
    "  }",
    "  for (var index = 0; index < artifacts.length; index += 1) {",
    "    var artifact = artifacts[index];",
    '    var link = document.createElement("a");',
    '    link.href = artifact.url || "#";',
    '    link.textContent = artifact.name + " (" + artifact.kind + ")";',
    '    link.target = "_blank";',
    '    link.rel = "noreferrer noopener";',
    "    executionArtifacts.appendChild(link);",
    "  }",
    "}",
    "",
    "function renderHealing(record) {",
    "  var healingEntries = collectHealingEntries(record);",
    "  if (!healingEntries.length) {",
    '    executionHealing.textContent = "Nenhuma recuperacao registrada.";',
    "    return;",
    "  }",
    "  var lines = [];",
    "  for (var index = 0; index < healingEntries.length; index += 1) {",
    "    var entry = healingEntries[index];",
    '    lines.push("Estrategia: " + entry.strategy);',
    '    lines.push("Selector original: " + entry.originalSelector);',
    '    lines.push("Selector recuperado: " + entry.recoveredSelector);',
    "    if (entry.suggestion && entry.suggestion.rationale) {",
    '      lines.push("Rationale: " + entry.suggestion.rationale);',
    "    }",
    "    if (index < healingEntries.length - 1) {",
    '      lines.push("");',
    "    }",
    "  }",
    '  executionHealing.textContent = lines.join("\\n");',
    "}",
    "",
    "function renderRecord(record) {",
    "  executionId.textContent = record.id;",
    "  executionStatus.textContent = record.status;",
    '  executionStatus.className = "status-" + record.status;',
    '  scenarioTitle.textContent = record.result && record.result.scenarioTitle ? record.result.scenarioTitle : "-";',
    '  var lines = ["URL: " + record.request.url, "Flow: " + record.request.flow, "", "Status: " + record.status];',
    "  renderSummary(record.result ? record.result.summary : null);",
    "  renderArtifacts(record);",
    "  renderHealing(record);",
    "  if (record.result && record.result.errorMessage) {",
    '    lines.push("Error: " + record.result.errorMessage);',
    "  }",
    "  if (record.result && record.result.plannedScenario && record.result.plannedScenario.steps) {",
    '    lines.push("", "Planned steps:");',
    "    for (var stepIndex = 0; stepIndex < record.result.plannedScenario.steps.length; stepIndex += 1) {",
    "      var step = record.result.plannedScenario.steps[stepIndex];",
    '      lines.push((stepIndex + 1) + ". [" + step.kind + "] " + step.description);',
    "    }",
    "  }",
    "  if (record.result && record.result.auditEntries && record.result.auditEntries.length) {",
    '    lines.push("", "Audit entries:");',
    "    for (var auditIndex = 0; auditIndex < record.result.auditEntries.length; auditIndex += 1) {",
    "      var entry = record.result.auditEntries[auditIndex];",
    '      lines.push("- [" + entry.type + "] " + entry.createdAt);',
    "      lines.push(JSON.stringify(entry.payload, null, 2));",
    "    }",
    "  }",
    '  executionLogs.textContent = lines.join("\\n");',
    "}",
    "",
    "async function pollExecution(id) {",
    "  if (pollingToken) {",
    "    clearInterval(pollingToken);",
    "  }",
    "  var refresh = async function () {",
    '    var response = await fetch("/api/executions/" + id);',
    "    var record = await response.json();",
    "    renderRecord(record);",
    '    if (record.status === "passed" || record.status === "failed") {',
    "      clearInterval(pollingToken);",
    "      pollingToken = null;",
    "    }",
    "  };",
    "  await refresh();",
    "  pollingToken = setInterval(refresh, 1000);",
    "}",
    "",
    'executeButton.addEventListener("click", async function () {',
    "  try {",
    "    var payload = { url: urlInput.value, flow: flowInput.value };",
    '    executionStatus.textContent = "running";',
    '    executionStatus.className = "status-running";',
    '    executionSummary.textContent = "Processando...";',
    '    executionArtifacts.textContent = "Processando...";',
    '    executionHealing.textContent = "Processando...";',
    '    executionLogs.textContent = "Criando execucao...";',
    '    var response = await fetch("/api/executions", {',
    '      method: "POST",',
    '      headers: { "Content-Type": "application/json" },',
    "      body: JSON.stringify(payload)",
    "    });",
    "    var record = await response.json();",
    "    renderRecord(record);",
    "    await pollExecution(record.id);",
    "  } catch (error) {",
    '    executionStatus.textContent = "failed";',
    '    executionStatus.className = "status-failed";',
    '    executionSummary.textContent = "Falha ao iniciar execucao.";',
    '    executionArtifacts.textContent = "Nenhuma evidencia registrada.";',
    '    executionHealing.textContent = "Nenhuma recuperacao registrada.";',
    "    executionLogs.textContent = String(error);",
    "  }",
    "});",
    "",
    'prefillButton.addEventListener("click", function () {',
    '  urlInput.value = "/fixtures/login-flow";',
    '  flowInput.value = "Open the login page, submit the form and validate the dashboard state.";',
    "});",
    "",
    'healingDemoButton.addEventListener("click", function () {',
    '  urlInput.value = "/fixtures/healing-login";',
    '  flowInput.value = "Abra a pagina, faca login com as credenciais abaixo e valide que o Dashboard ficou visivel:\\n- email: qa@secondmind.dev\\n- senha: super-secret";',
    "});"
  ].join("\n");
}
